title: "Bussière Respire"
description: "Comprendre notre ville, imaginer son avenir."
lang: fr
baseurl: "/site"
url: "https://bussiere-respire.github.io"
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github/
